{
 "title": "MediaDB",
 "description": "Shows statistics for existing media and transcoding operations.",
 "tags": [
  "Transcode Stats",
  "favorites"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Shows/Movies Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Percent of Original Size All Time",
   "type": "gauge",
   "description": "Shows the all time percent of storage saved by transcoding.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT existspercent, added, tablename \r\nFROM StatisticsLive WHERE tablename = 'Shows'\r\n",
     "rawQueryText": "SELECT existspercent, added, tablename \r\nFROM StatisticsLive WHERE tablename = 'Shows'\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT existspercent, added, tablename \r\nFROM StatisticsLive WHERE tablename = 'Movies'\r\n",
     "rawQueryText": "SELECT existspercent, added, tablename \r\nFROM StatisticsLive WHERE tablename = 'Movies'\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "File Count",
   "type": "stat",
   "description": "Total number of existing media files.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT mediacount, added\r\nFrom StatisticsLive WHERE tablename = 'Shows'\r\n--ORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT mediacount, added\r\nFrom StatisticsLive WHERE tablename = 'Shows'\r\n--ORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT mediacount, added\r\nFrom StatisticsLive WHERE tablename = 'Movies'\r\n--ORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT mediacount, added\r\nFrom StatisticsLive WHERE tablename = 'Movies'\r\n--ORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Storage Saved All Time",
   "type": "stat",
   "description": "All Time storage saved from transcoding.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT existsdifferenceMB, added\r\nFROM StatisticsLive WHERE tablename = 'Shows'\r\n--ORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existsdifferenceMB, added\r\nFROM StatisticsLive WHERE tablename = 'Shows'\r\n--ORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT existsdifferenceMB, added\r\nFROM StatisticsLive WHERE tablename = 'Movies'\r\n--ORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existsdifferenceMB, added\r\nFROM StatisticsLive WHERE tablename = 'Movies'\r\n--ORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Storage Usage",
   "type": "stat",
   "description": "Total storage used by media files.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT existssumsizeMB, added\r\nFROM StatisticsLive WHERE tablename = 'Shows'\r\n--ORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existssumsizeMB, added\r\nFROM StatisticsLive WHERE tablename = 'Shows'\r\n--ORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT existssumsizeMB, added\r\nFROM StatisticsLive WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existssumsizeMB, added\r\nFROM StatisticsLive WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Increased Disk usage Shows",
   "type": "stat",
   "description": "Shows the growth in storage usage over time. Useful in predicting when additional storage will be required.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT growth30daysMB, growth90daysMB, growth180daysMB, growth365daysMB, added\r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added LIMIT 365",
     "rawQueryText": "SELECT growth30daysMB, growth90daysMB, growth180daysMB, growth365daysMB, added\r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added LIMIT 365",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Increased Disk usage Movies",
   "type": "stat",
   "description": "Shows the growth in storage usage over time. Useful in predicting when additional storage will be required.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT growth30daysMB, growth90daysMB, growth180daysMB, growth365daysMB, added\r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added LIMIT 365",
     "rawQueryText": "SELECT growth30daysMB, growth90daysMB, growth180daysMB, growth365daysMB, added\r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added LIMIT 365",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Shows Percent of Original Size Over Time",
   "type": "gauge",
   "description": "Graph helps to illustrate how changes in the media sources or transcoding parameters result in changes to file size over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Shows\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-30 day')",
     "rawQueryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Shows\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-30 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\nFROM Shows\nWHERE fileexists = 'true'\n  And added > DATETIME('now', '-90 day')",
     "rawQueryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\nFROM Shows\nWHERE fileexists = 'true'\n  And added > DATETIME('now', '-90 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\nFROM Shows\nWHERE fileexists = 'true'\n  And added > DATETIME('now', '-180 day')",
     "rawQueryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\nFROM Shows\nWHERE fileexists = 'true'\n  And added > DATETIME('now', '-180 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\nFROM Shows\nWHERE fileexists = 'true'\n  And added > DATETIME('now', '-365 day')",
     "rawQueryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\nFROM Shows\nWHERE fileexists = 'true'\n  And added > DATETIME('now', '-365 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Movies Percent of Original Size over Time",
   "type": "gauge",
   "description": "Graph helps to illustrate how changes in the media sources or transcoding parameters result in changes to file size over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Movies\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-30 day')",
     "rawQueryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Movies\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-30 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Movies\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-90 day')",
     "rawQueryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Movies\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-90 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Movies\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-180 day')",
     "rawQueryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Movies\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-180 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Movies\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-365 day')",
     "rawQueryText": "SELECT (100 / sum(oldsizeMB)) * sum(newsizeMB)\r\nFROM Movies\r\nWHERE fileexists = 'true'\r\n  And added > DATETIME('now', '-365 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Count of Added", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "30 Days Shows",
   "type": "stat",
   "description": "Simply shows the number of added media files in a given time period.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM Shows WHERE fileexists = 'true' AND added > DATETIME('now', '-30 day')",
     "rawQueryText": "SELECT * FROM Shows WHERE fileexists = 'true' AND added > DATETIME('now', '-30 day')"
    }
   ]
  },
  {
   "title": "90 Days Shows",
   "type": "stat",
   "description": "Simply shows the number of added media files in a given time period.",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM Shows WHERE fileexists = 'true' AND added > DATETIME('now', '-90 day')",
     "rawQueryText": "SELECT * FROM Shows WHERE fileexists = 'true' AND added > DATETIME('now', '-90 day')"
    }
   ]
  },
  {
   "title": "30 Days Movies",
   "type": "stat",
   "description": "Simply shows the number of added media files in a given time period.",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM Movies WHERE fileexists = 'true' AND added > DATETIME('now', '-30 day')",
     "rawQueryText": "SELECT * FROM Movies WHERE fileexists = 'true' AND added > DATETIME('now', '-30 day')"
    }
   ]
  },
  {
   "title": "90 Days Movies",
   "type": "stat",
   "description": "Simply shows the number of added media files in a given time period.",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM Movies WHERE fileexists = 'true' AND added > DATETIME('now', '-90 day')",
     "rawQueryText": "SELECT * FROM Movies WHERE fileexists = 'true' AND added > DATETIME('now', '-90 day')"
    }
   ]
  },
  {
   "title": "180 Days Shows",
   "type": "stat",
   "description": "Simply shows the number of added media files in a given time period.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM Shows WHERE fileexists = 'true' AND added > DATETIME('now', '-180 day')",
     "rawQueryText": "SELECT * FROM Shows WHERE fileexists = 'true' AND added > DATETIME('now', '-180 day')"
    }
   ]
  },
  {
   "title": "365 Days Shows",
   "type": "stat",
   "description": "Simply shows the number of added media files in a given time period.",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM Shows WHERE fileexists = 'true' AND added > DATETIME('now', '-365 day')",
     "rawQueryText": "SELECT * FROM Shows WHERE fileexists = 'true' AND added > DATETIME('now', '-365 day')"
    }
   ]
  },
  {
   "title": "180 Days Movies",
   "type": "stat",
   "description": "Simply shows the number of added media files in a given time period.",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM Movies WHERE fileexists = 'true' AND added > DATETIME('now', '-180 day')",
     "rawQueryText": "SELECT * FROM Movies WHERE fileexists = 'true' AND added > DATETIME('now', '-180 day')"
    }
   ]
  },
  {
   "title": "365 Days Movies",
   "type": "stat",
   "description": "Simply shows the number of added media files in a given time period.",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM Movies WHERE fileexists = 'true' AND added > DATETIME('now', '-365 day')",
     "rawQueryText": "SELECT * FROM Movies WHERE fileexists = 'true' AND added > DATETIME('now', '-365 day')"
    }
   ]
  },
  {
   "title": "Movies Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Movies",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "queryText": "SELECT * From Movies",
       "rawQueryText": "SELECT * From Movies",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Shows Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shows",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "queryText": "Select * From Shows",
       "rawQueryText": "Select * From Shows",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statistics",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "queryText": "SELECT * From Statistics",
       "rawQueryText": "SELECT * From Statistics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}