{
 "title": "MediaDB",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Shows/Movies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT existspercent, added, tablename \r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existspercent, added, tablename \r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT existspercent, added, tablename \r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existspercent, added, tablename \r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT mediacount, added\r\nFrom Statistics WHERE tablename = 'Shows'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT mediacount, added\r\nFrom Statistics WHERE tablename = 'Shows'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT mediacount, added\r\nFrom Statistics WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT mediacount, added\r\nFrom Statistics WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT existsdifferenceMB, added\r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existsdifferenceMB, added\r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT existsdifferenceMB, added\r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existsdifferenceMB, added\r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT existssumsizeMB, added\r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existssumsizeMB, added\r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT existssumsizeMB, added\r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "rawQueryText": "SELECT existssumsizeMB, added\r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Increased Disk usage Shows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT growth30daysMB, growth90daysMB, growth180daysMB, growth365daysMB, added\r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added LIMIT 365",
     "rawQueryText": "SELECT growth30daysMB, growth90daysMB, growth180daysMB, growth365daysMB, added\r\nFROM Statistics WHERE tablename = 'Shows'\r\nORDER BY added LIMIT 365",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Increased Disk usage Movies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT growth30daysMB, growth90daysMB, growth180daysMB, growth365daysMB, added\r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added LIMIT 365",
     "rawQueryText": "SELECT growth30daysMB, growth90daysMB, growth180daysMB, growth365daysMB, added\r\nFROM Statistics WHERE tablename = 'Movies'\r\nORDER BY added LIMIT 365",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "queryText": "SELECT * From Movies",
     "rawQueryText": "SELECT * From Movies",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Shows",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "queryText": "Select * From Shows",
     "rawQueryText": "Select * From Shows",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "queryText": "SELECT * From Statistics",
     "rawQueryText": "SELECT * From Statistics",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}