name: dev-alpine3.17-amd64

"on":
  #  pull_request:
  #    types:
  #      - opened
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag
        id: repository
        run: echo "tag=$(cat version)" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN }}

      - name: Build and push alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.alpine3.17-amd64
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/thetaylorlee/docker-transcodeautomation:alpine3.17-amd64-develop-${{ env.tag }}
            ghcr.io/thetaylorlee/docker-transcodeautomation:alpine3.17-amd64-develop
