name: dev images

"on":
  workflow_dispatch:
    tags:
      - "*"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag
        id: repository
        run: echo "tag=$(git describe --tags HEAD)" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN }}

      - name: Build and push alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          registry: ghcr.io
          platforms: linux/amd64,linux/arm64
          push: true
          dockerfile: Dockerfile.alpine3.14-lts
          tags: ghcr.io/thetaylorlee/docker-transcodeautomation:alpine3.14-lts-development

      - name: Build and push ubuntu
        uses: docker/build-push-action@v3
        with:
          context: .
          registry: ghcr.io
          platforms: linux/amd64,linux/arm64
          push: true
          dockerfile: Dockerfile.ubuntu22.04-lts
          tags: ghcr.io/thetaylorlee/docker-transcodeautomation:ubuntu22.04-lts-development
